### ISSUE TITLE
Storing Runs

### ISSUE THREAD

**Issue by davidnoz123** [maskarsaket/DeepFlow#25]
When we see the points on the performance chart we will invariably ask something like "can we redo run x with y and z changed" ... it's quite hard to recreate the exact conditions for a run ... unless ... we capture most if not all of the code and data at the time of the run!!

Write code that is triggered when we do a solve run to capture the code, parameter files, command lines and input data and put it in a .zip file.

Write a tool to extract the .zip and recreate the run.

We could look at some system that stores only the deltas between consecutive runs.

We could look at something that runs in parallel with the solve run so we don't delay the start of the solve run.

**Comment by maskarsaket** [comment]
Thanks for the suggestion, sounds awesome.
For starters I can implement the capturing of codes, parameters, input data and command line args into a zip file and save it into the Artefacts folder for each experiment.
For the delta between consecutive runs we could probably integrate git to create a new branch or tag for each experiment?

**Comment by davidnoz123** [comment]
The delta idea was meant in the sense of https://rsync.samba.org/The idea is that we store the increments calculated by rsync (or something like it).That way we can rebuild a set of files using only the deltas associated with some previous set of files.We will have a "chain" of deltas that can recreate a set of files from some 'base'.This will save loads of memory and make it really fast!! 
CheersDavid

    On Friday, 8 May 2020, 15:25:25 GMT+12, Saket Maskara <notifications@github.com> wrote:  
 
 


Thanks for the suggestion, sounds awesome.
For starters I can implement the capturing of codes, parameters, input data and command line args into a zip file and save it into the Artefacts folder for each experiment.
For the delta between consecutive runs we could probably integrate git to create a new branch or tag for each experiment?

**Comment by maskarsaket** [comment]
I had not heard about that before, thanks for the information. I'll research about it over the weekend and get back to you. This would definitely save loads of space.
